services:
  
  bob:
    container_name: bob
    hostname: bob
    build: .
    command: "sh -c 'tc qdisc add dev eth0 root netem delay 1ms && demon --cluster-size 3 --proto demon'"
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:80

  alice:
    container_name: alice
    hostname: alice
    build: .
    command: "sh -c 'tc qdisc add dev eth0 root netem delay 1ms && demon --cluster-size 3 --proto demon --addr bob:1234'"
    cap_add:
      - NET_ADMIN
    ports:
      - 8081:80
    environment:
      RUST_BACKTRACE: 1
    depends_on:
      - bob

  fabi:
    container_name: fabi
    hostname: fabi
    build: .
    command: "sh -c 'tc qdisc add dev eth0 root netem delay 1ms && demon --cluster-size 3 --proto demon --addr bob:1234'"
    cap_add:
      - NET_ADMIN
    ports:
      - 8082:80
    depends_on:
      - bob
