services:
  
  bob:
    container_name: bob
    hostname: bob
    build: .
    command: demon

  alice:
    container_name: alice
    hostname: alice
    build: .
    command: demon bob:1234
    environment:
      RUST_BACKTRACE: 1
    depends_on:
      - bob

  fabi:
    container_name: fabi
    hostname: fabi
    build: .
    command: demon bob:1234
    depends_on:
      - bob
