services:
  
  bob:
    container_name: bob
    hostname: bob
    build: 
      context: .
      dockerfile: Dockerfile
    # command: --cluster-size 3 --proto demon -t tpcc
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:80
      - 5000:5000

  alice:
    container_name: alice
    hostname: alice
    build: 
      context: .
      dockerfile: Dockerfile
    # command: --cluster-size 3 --proto demon -t tpcc --addr bob:1234
    cap_add:
      - NET_ADMIN
    ports:
      - 8081:80
      - 5001:5000
    environment:
      RUST_BACKTRACE: 1
    depends_on:
      - bob

  fabi:
    container_name: fabi
    hostname: fabi
    build: 
      context: .
      dockerfile: Dockerfile
    # command: --cluster-size 3 --proto demon -t tpcc --addr bob:1234
    cap_add:
      - NET_ADMIN
    ports:
      - 8082:80
      - 5002:5000
    depends_on:
      - bob
