services:
  
  bob:
    container_name: bob
    hostname: bob
    build: .
    command: demon --cluster-size 3 --proto demon
    ports:
      - 8080:80

  alice:
    container_name: alice
    hostname: alice
    build: .
    command: demon --cluster-size 3 --proto demon --addr bob:1234
    ports:
      - 8081:80
    environment:
      RUST_BACKTRACE: 1
    depends_on:
      - bob

  fabi:
    container_name: fabi
    hostname: fabi
    build: .
    command: demon --cluster-size 3 --proto demon --addr bob:1234
    ports:
      - 8082:80
    depends_on:
      - bob
